In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

[0 1 2 3 4 5]


In [4]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [5]:
c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [6]:
a = np.array([[0, 1, 2], [3, 4, 5]])
c = np.array([[2, 0, 1], [5, 3, 4]])
print(a)
print()
print(c)
print()
print(b + c)
print()
print(b * c)


[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


In [7]:
d = np.array([[1, 1], [1, 1]])
e = np.array([1, 2])

print(d + e)

[[2 3]
 [2 3]]


In [8]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a.shape)

(2, 3)


In [9]:
b = np.array([0, 1, 2, 3, 4, 5, 6, 7])
c = b.reshape(2, 4)
print(c)

[[0 1 2 3]
 [4 5 6 7]]


In [13]:
d = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])
e = d.reshape(-1)
print(e)

[0 1 2 3 4 5 5 4 3 2 1 0]


In [14]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a[2])

2


In [15]:
a[2] = 9
print(a)

[0 1 9 3 4 5]


In [17]:
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b[1, 2])

5


In [18]:
b[1, 2] = 9
print(b)

[[0 1 2]
 [3 4 9]]


In [19]:
def my_func(x):
  y = x * 2 + 1
  return y

a = np.array([[0, 1, 2], [3, 4, 5]])
b = my_func(a)

print(b)

[[ 1  3  5]
 [ 7  9 11]]


In [21]:
a = np.array([[0, 1, 2], [3, 4, 5]])

print(np.sum(a))
print(np.average(a))
print(np.max(a))
print(np.min(a))

15
2.5
5
0


In [22]:
b = np.array([[0, 1, 2], [3, 4, 5]])

print(np.sum(b, axis=0))
print(np.sum(b, axis=1))

[3 5 7]
[ 3 12]
