In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)

b = np.array([-2.3, 0.25, -1.2, 1.8, 0.41])
print(b)

[1 2 3]
[-2.3   0.25 -1.2   1.8   0.41]


In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


In [8]:
a = np.array([[[0, 1, 2, 3],
               [2, 3, 4, 5],
               [4, 5, 6, 7]],
              [[1, 2, 3, 4],
               [3, 4, 5, 6],
               [5, 6, 7, 8]]])
print(a)               

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


In [9]:
a = [[0, 1, 2],
     [1, 2, 3]]

b = [[2, 1],
     [2, 1],
     [2, 1]]     

print(np.dot(a, b))     

[[ 6  3]
 [12  6]]


In [11]:
a = np.array([[0, 1, 2],
     [3, 4, 5],
     [6, 7, 8]])
b = np.array([[0, 1, 2],
             [2, 0, 1],
             [1, 2, 0]])     

print(a*b)


[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [12]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)              

[[1 4]
 [2 5]
 [3 6]]
